// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqHdWNpnVB5plGG0qcfKHB5JqU8xkObPk',
    appId: '1:210391832763:web:37004eb91f6192a565719e',
    messagingSenderId: '210391832763',
    projectId: 'database-aplikasi-a0757',
    authDomain: 'database-aplikasi-a0757.firebaseapp.com',
    databaseURL: 'https://database-aplikasi-a0757-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'database-aplikasi-a0757.firebasestorage.app',
    measurementId: 'G-W5JZ51J1R0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW8qI6_GiSQx3tphKodN2XuIkwfwT25WA',
    appId: '1:210391832763:android:0cd5f36bc9fe674a65719e',
    messagingSenderId: '210391832763',
    projectId: 'database-aplikasi-a0757',
    databaseURL: 'https://database-aplikasi-a0757-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'database-aplikasi-a0757.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1E6EzsYEGka_Lfhc-UHsXs90GMXF-DjE',
    appId: '1:210391832763:ios:fb3c44d6f123af0565719e',
    messagingSenderId: '210391832763',
    projectId: 'database-aplikasi-a0757',
    databaseURL: 'https://database-aplikasi-a0757-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'database-aplikasi-a0757.firebasestorage.app',
    iosClientId: '210391832763-cjsu2k2pp3gfj4qotp4orar3jn0n34cp.apps.googleusercontent.com',
    iosBundleId: 'com.example.appIot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1E6EzsYEGka_Lfhc-UHsXs90GMXF-DjE',
    appId: '1:210391832763:ios:fb3c44d6f123af0565719e',
    messagingSenderId: '210391832763',
    projectId: 'database-aplikasi-a0757',
    databaseURL: 'https://database-aplikasi-a0757-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'database-aplikasi-a0757.firebasestorage.app',
    iosClientId: '210391832763-cjsu2k2pp3gfj4qotp4orar3jn0n34cp.apps.googleusercontent.com',
    iosBundleId: 'com.example.appIot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqHdWNpnVB5plGG0qcfKHB5JqU8xkObPk',
    appId: '1:210391832763:web:804faf4da1ff3a9565719e',
    messagingSenderId: '210391832763',
    projectId: 'database-aplikasi-a0757',
    authDomain: 'database-aplikasi-a0757.firebaseapp.com',
    databaseURL: 'https://database-aplikasi-a0757-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'database-aplikasi-a0757.firebasestorage.app',
    measurementId: 'G-JTWXH9TW84',
  );
}
